/**
 * DiagramUploadPanel - Admin panel for DIAGRAM_LABEL_COMPLETION questions
 * 
 * Displays the AI-generated diagram_description and allows admin to:
 * 1. View the detailed diagram description
 * 2. Enter/upload an image URL for the diagram
 * 
 * The diagram_description is generated by the AI with detailed instructions
 * for the admin to create or source the appropriate diagram image.
 * 
 * @since 2025-12-26
 */

import React, { useState } from 'react';
import { FiImage, FiInfo, FiCheck, FiExternalLink, FiChevronDown, FiChevronUp } from 'react-icons/fi';
import useABTSStore from '../../stores/useABTSStore';
import './AIStudio.css';

export default function DiagramUploadPanel({ 
    questions,      // Array of DIAGRAM_LABEL_COMPLETION questions in this group
    startNum,       // First question number in the group
    endNum          // Last question number in the group
}) {
    const updateQuestionImageUrl = useABTSStore(state => state.updateQuestionImageUrl);
    
    const [imageUrl, setImageUrl] = useState('');
    const [isDescriptionExpanded, setIsDescriptionExpanded] = useState(true);
    const [isSaved, setIsSaved] = useState(false);

    // Get the diagram description from the first question (shared across group)
    const firstQuestion = questions[0];
    const diagramDescription = firstQuestion?.questionContent?.diagram_description || 
                               firstQuestion?.questionContent?.diagramDescription || 
                               null;
    
    // Check if any question already has an imageUrl
    const existingImageUrl = questions.find(q => q.imageUrl)?.imageUrl || '';

    // Handle image URL save
    const handleSaveImageUrl = () => {
        if (!imageUrl.trim()) return;
        
        // Update all questions in the group with the same imageUrl
        questions.forEach(q => {
            updateQuestionImageUrl(q.questionNumber, imageUrl.trim());
        });
        
        setIsSaved(true);
        setTimeout(() => setIsSaved(false), 2000);
    };

    // Handle Enter key
    const handleKeyPress = (e) => {
        if (e.key === 'Enter') {
            handleSaveImageUrl();
        }
    };

    // Initialize with existing URL if present
    React.useEffect(() => {
        if (existingImageUrl && !imageUrl) {
            setImageUrl(existingImageUrl);
        }
    }, [existingImageUrl]);

    return (
        <div className="studio-diagram-panel">
            {/* Header */}
            <div className="studio-diagram-panel__header">
                <div className="studio-diagram-panel__title">
                    <FiImage size={16} />
                    <span>Diagram Required (Q{startNum}-{endNum})</span>
                </div>
                <span className="studio-diagram-panel__badge">
                    DIAGRAM_LABEL_COMPLETION
                </span>
            </div>

            {/* Diagram Description Section */}
            {diagramDescription && (
                <div className="studio-diagram-panel__description-section">
                    <button 
                        className="studio-diagram-panel__description-toggle"
                        onClick={() => setIsDescriptionExpanded(!isDescriptionExpanded)}
                    >
                        <FiInfo size={14} />
                        <span>AI Diagram Description</span>
                        {isDescriptionExpanded ? <FiChevronUp size={14} /> : <FiChevronDown size={14} />}
                    </button>
                    
                    {isDescriptionExpanded && (
                        <div className="studio-diagram-panel__description">
                            <p className="studio-diagram-panel__description-hint">
                                Use this description to create or source the diagram image:
                            </p>
                            <div className="studio-diagram-panel__description-text">
                                {diagramDescription}
                            </div>
                        </div>
                    )}
                </div>
            )}

            {/* No Description Warning */}
            {!diagramDescription && (
                <div className="studio-diagram-panel__warning">
                    <FiInfo size={14} />
                    <span>No diagram description was generated. You'll need to create the diagram based on the passage content.</span>
                </div>
            )}

            {/* Image URL Input Section */}
            <div className="studio-diagram-panel__upload-section">
                <label className="studio-diagram-panel__label">
                    Image URL
                    <span className="studio-diagram-panel__label-hint">
                        (Paste a URL or upload to your image host)
                    </span>
                </label>
                
                <div className="studio-diagram-panel__input-row">
                    <input
                        type="url"
                        className="studio-diagram-panel__input"
                        placeholder="https://example.com/diagram.png"
                        value={imageUrl}
                        onChange={(e) => setImageUrl(e.target.value)}
                        onKeyPress={handleKeyPress}
                    />
                    <button
                        className={`studio-diagram-panel__save-btn ${isSaved ? 'studio-diagram-panel__save-btn--saved' : ''}`}
                        onClick={handleSaveImageUrl}
                        disabled={!imageUrl.trim()}
                    >
                        {isSaved ? (
                            <>
                                <FiCheck size={14} />
                                Saved
                            </>
                        ) : (
                            'Apply to All'
                        )}
                    </button>
                </div>

                {/* Preview */}
                {(imageUrl || existingImageUrl) && (
                    <div className="studio-diagram-panel__preview">
                        <div className="studio-diagram-panel__preview-header">
                            <span>Preview</span>
                            <a 
                                href={imageUrl || existingImageUrl} 
                                target="_blank" 
                                rel="noopener noreferrer"
                                className="studio-diagram-panel__preview-link"
                            >
                                <FiExternalLink size={12} />
                                Open in new tab
                            </a>
                        </div>
                        <img 
                            src={imageUrl || existingImageUrl} 
                            alt="Diagram preview" 
                            className="studio-diagram-panel__preview-image"
                            onError={(e) => {
                                e.target.style.display = 'none';
                                e.target.nextSibling.style.display = 'block';
                            }}
                        />
                        <div className="studio-diagram-panel__preview-error" style={{ display: 'none' }}>
                            Failed to load image. Please check the URL.
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
