package com.cramer.config;

import com.cramer.entity.TestSet;
import com.cramer.repository.TestSetRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
@Slf4j
public class DataSeeder implements CommandLineRunner {

    private final TestSetRepository testSetRepository;

    @Override
    public void run(String... args) throws Exception {
        seedTestSets();
    }

    private void seedTestSets() {
        if (!testSetRepository.existsByCode("ai_generated")) {
            log.info("Seeding 'ai_generated' TestSet...");

            TestSet aiSet = TestSet.builder()
                    .code("ai_generated")
                    .nameVi("Đề thi AI Tạo")
                    .nameEn("AI Generated Tests")
                    .description("Collection of tests generated by AI assistant.")
                    .sourceType("ai_generated")
                    .isPublished(false) // Default to DRAFT
                    .isSystem(true)
                    .displayOrder(999) // Show at the end
                    .build();

            testSetRepository.save(aiSet);
            log.info("'ai_generated' TestSet created successfully.");
        } else {
            // FIX: Ensure existing set is DRAFT if it was previously created as PUBLISHED
            testSetRepository.findByCode("ai_generated").ifPresent(set -> {
                if (Boolean.TRUE.equals(set.getIsPublished())) {
                    set.setIsPublished(false);
                    testSetRepository.save(set);
                    log.info("Fixed 'ai_generated' TestSet status to DRAFT.");
                }
            });
            log.debug("'ai_generated' TestSet already exists.");
        }
    }
}
